[workspace]
members = ["cargo:."]

# Config for 'dist'
[dist]
ci = "github"
cargo-dist-version = "0.32.0"

installers = ["shell"]
install-path = ["$XDG_BIN_HOME/", "$XDG_DATA_HOME/../bin", "~/.local/bin"]

targets = ["aarch64-apple-darwin", "aarch64-unknown-linux-gnu", "x86_64-apple-darwin", "x86_64-unknown-linux-gnu"]
