use crate::dsl::spec::{Cardinality, NameDesc, Place, RuleDesc, SPEC, Spec};
use clap::{Arg, ArgMatches, Command};
use std::env;
use std::fmt::Write as _;
use std::fs;
use std::io;
use std::path::{Path, PathBuf};
use thiserror::Error;

const SKILL_NAME: &str = "bts";
const GENERATED_MARKER: &str = "<!-- Generated by `bts setup skill`; changes will be overwritten. -->";

#[derive(Debug, Clone, Copy, Eq, PartialEq)]
enum Agent {
    Codex,
    Claude,
}

impl Agent {
    fn parse(value: &str) -> Self {
        match value {
            "codex" => Self::Codex,
            "claude" => Self::Claude,
            _ => unreachable!("clap restricts --agent to known values"),
        }
    }
}

#[derive(Debug, Clone, Copy, Eq, PartialEq)]
enum Scope {
    Local,
    User,
    Global,
}

impl Scope {
    fn parse(value: &str) -> Self {
        match value {
            "local" => Self::Local,
            "user" => Self::User,
            "global" => Self::Global,
            _ => unreachable!("clap restricts scope to known values"),
        }
    }
}

#[derive(Debug, Error)]
enum SetupError {
    #[error("could not determine the current directory: {0}")]
    CurrentDirectory(#[source] io::Error),
    #[error("could not determine the user home directory")]
    MissingHome,
    #[error(
        "Claude Code does not support a global filesystem skill directory; use local or user scope, or deploy the skill through Claude managed configuration"
    )]
    UnsupportedClaudeGlobal,
    #[cfg(windows)]
    #[error("Codex does not document a global filesystem skill directory on Windows; use local or user scope")]
    UnsupportedCodexGlobal,
    #[error("could not create skill directory {path}: {source}")]
    CreateDirectory {
        path: PathBuf,
        #[source]
        source: io::Error,
    },
    #[error("could not read existing skill {path}: {source}")]
    ReadExisting {
        path: PathBuf,
        #[source]
        source: io::Error,
    },
    #[error("refusing to overwrite {0} because it was not generated by bts")]
    UnmanagedSkill(PathBuf),
    #[error("could not write skill {path}: {source}")]
    WriteSkill {
        path: PathBuf,
        #[source]
        source: io::Error,
    },
}

pub fn command() -> Command {
    Command::new("setup")
        .about("set up integrations for bts")
        .subcommand_required(true)
        .arg_required_else_help(true)
        .subcommand(
            Command::new("skill")
                .visible_alias("skills")
                .about("generate and install the bts agent skill")
                .arg(
                    Arg::new("scope")
                        .value_name("SCOPE")
                        .help("installation scope")
                        .value_parser(["local", "user", "global"])
                        .default_value("local"),
                )
                .arg(
                    Arg::new("agent")
                        .long("agent")
                        .value_name("AGENT")
                        .help("agent for which to install the skill")
                        .value_parser(["codex", "claude"])
                        .required(true),
                ),
        )
}

pub fn run(matches: &ArgMatches) -> bool {
    let Some(("skill", matches)) = matches.subcommand() else {
        return false;
    };

    let agent = Agent::parse(matches.get_one::<String>("agent").expect("clap requires --agent"));
    let scope = Scope::parse(matches.get_one::<String>("scope").expect("clap supplies a default scope"));

    match install_skill(agent, scope) {
        Ok(path) => {
            println!("installed bts skill at {}", path.display());
            true
        }
        Err(error) => {
            eprintln!("error: {error}");
            false
        }
    }
}

fn install_skill(agent: Agent, scope: Scope) -> Result<PathBuf, SetupError> {
    let current_dir = env::current_dir().map_err(SetupError::CurrentDirectory)?;
    let home_dir = user_home_dir();
    let claude_config_dir = env::var_os("CLAUDE_CONFIG_DIR")
        .filter(|value| !value.is_empty())
        .map(PathBuf::from);
    let skill_dir = skill_dir(agent, scope, &current_dir, home_dir.as_deref(), claude_config_dir.as_deref())?;

    write_skill(&skill_dir, &render_skill(&SPEC))
}

fn user_home_dir() -> Option<PathBuf> {
    env::var_os("HOME")
        .filter(|value| !value.is_empty())
        .or_else(|| env::var_os("USERPROFILE").filter(|value| !value.is_empty()))
        .map(PathBuf::from)
}

fn skill_dir(
    agent: Agent,
    scope: Scope,
    current_dir: &Path,
    home_dir: Option<&Path>,
    claude_config_dir: Option<&Path>,
) -> Result<PathBuf, SetupError> {
    let root = match (agent, scope) {
        (Agent::Codex, Scope::Local) => current_dir.join(".agents/skills"),
        (Agent::Claude, Scope::Local) => current_dir.join(".claude/skills"),
        (Agent::Codex, Scope::User) => home_dir.ok_or(SetupError::MissingHome)?.join(".agents/skills"),
        (Agent::Claude, Scope::User) => match claude_config_dir {
            Some(config_dir) => config_dir.join("skills"),
            None => home_dir.ok_or(SetupError::MissingHome)?.join(".claude/skills"),
        },
        (Agent::Claude, Scope::Global) => return Err(SetupError::UnsupportedClaudeGlobal),
        #[cfg(not(windows))]
        (Agent::Codex, Scope::Global) => PathBuf::from("/etc/codex/skills"),
        #[cfg(windows)]
        (Agent::Codex, Scope::Global) => return Err(SetupError::UnsupportedCodexGlobal),
    };

    Ok(root.join(SKILL_NAME))
}

fn write_skill(skill_dir: &Path, contents: &str) -> Result<PathBuf, SetupError> {
    fs::create_dir_all(skill_dir).map_err(|source| SetupError::CreateDirectory {
        path: skill_dir.to_owned(),
        source,
    })?;

    let path = skill_dir.join("SKILL.md");
    if path.exists() {
        let existing = fs::read_to_string(&path).map_err(|source| SetupError::ReadExisting {
            path: path.clone(),
            source,
        })?;
        if !existing.contains(GENERATED_MARKER) {
            return Err(SetupError::UnmanagedSkill(path));
        }
    }

    fs::write(&path, contents).map_err(|source| SetupError::WriteSkill {
        path: path.clone(),
        source,
    })?;

    Ok(path)
}

fn render_skill(spec: &Spec) -> String {
    let mut output = String::new();

    writeln!(output, "---").unwrap();
    writeln!(output, "name: {SKILL_NAME}").unwrap();
    writeln!(
        output,
        "description: Write, review, explain, and debug bts language source. Use when working with bts files, synthetic trace definitions, or bts syntax and validation errors."
    )
    .unwrap();
    writeln!(output, "---\n").unwrap();
    writeln!(output, "{GENERATED_MARKER}\n").unwrap();
    writeln!(output, "# {} language\n", spec.name).unwrap();
    writeln!(output, "{}\n", spec.summary).unwrap();
    writeln!(output, "## Workflow\n").unwrap();
    writeln!(
        output,
        "1. Read the language reference below before creating or changing bts source."
    )
    .unwrap();
    writeln!(
        output,
        "2. Use only the documented blocks, fields, expressions, placements, and rules."
    )
    .unwrap();
    writeln!(
        output,
        "3. Preserve the user's intent while making the smallest valid change."
    )
    .unwrap();
    writeln!(
        output,
        "4. Validate file-based source with `bts check --file <path>` after editing.\n"
    )
    .unwrap();
    writeln!(
        output,
        "5. Preview generated Braintrust events with `bts generate --from <path> --count <traces> --over <duration> --dry-run`."
    )
    .unwrap();
    writeln!(
        output,
        "6. When the user requests a live write, set `BRAINTRUST_API_KEY` and `BRAINTRUST_PROJECT_ID`, then rerun without `--dry-run`.\n"
    )
    .unwrap();
    writeln!(
        output,
        "Treat this generated reference as authoritative for BTS language version {} (specification schema version {}).\n",
        spec.language_version, spec.schema_version
    )
    .unwrap();

    writeln!(output, "## Surface grammar\n").unwrap();
    writeln!(output, "Notation: {}\n", spec.surface.notation).unwrap();
    writeln!(output, "{}", fenced_code("ebnf", spec.surface.grammar.trim())).unwrap();

    if !spec.surface.notes.is_empty() {
        writeln!(output, "### Syntax notes\n").unwrap();
        for note in spec.surface.notes {
            writeln!(output, "- {note}").unwrap();
        }
        writeln!(output).unwrap();
    }

    writeln!(output, "## Expression forms\n").unwrap();
    for expression in spec.expressions {
        writeln!(output, "### {}\n", inline_code(expression.id.as_str())).unwrap();
        writeln!(output, "{}\n", expression.summary).unwrap();
        writeln!(output, "Syntax: {}\n", inline_code(expression.syntax)).unwrap();
        if !expression.examples.is_empty() {
            writeln!(output, "Examples:").unwrap();
            for example in expression.examples {
                writeln!(output, "- {}", inline_code(example)).unwrap();
            }
            writeln!(output).unwrap();
        }
        render_rules(&mut output, expression.rules);
    }

    if !spec.functions.is_empty() {
        writeln!(output, "## Functions\n").unwrap();
        for function in spec.functions {
            writeln!(output, "### {}\n", inline_code(function.name)).unwrap();
            writeln!(output, "{}\n", function.summary).unwrap();
            writeln!(output, "Syntax: {}\n", inline_code(function.syntax)).unwrap();
            if !function.examples.is_empty() {
                writeln!(output, "Examples:").unwrap();
                for example in function.examples {
                    writeln!(output, "- {}", inline_code(example)).unwrap();
                }
                writeln!(output).unwrap();
            }
            render_rules(&mut output, function.rules);
        }
    }

    writeln!(output, "## Blocks\n").unwrap();
    for block in spec.blocks {
        writeln!(output, "### {}\n", inline_code(block.keyword)).unwrap();
        writeln!(output, "{}\n", block.summary).unwrap();
        writeln!(output, "- Syntax: {}", inline_code(block.syntax)).unwrap();
        writeln!(output, "- Name: {}", name_requirement(block.name)).unwrap();
        writeln!(output, "- Allowed in: {}", placements(spec, block.allowed_in)).unwrap();
        writeln!(
            output,
            "- Unlisted fields: {}\n",
            if block.body.open { "allowed" } else { "rejected" }
        )
        .unwrap();

        if !block.body.fields.is_empty() {
            writeln!(output, "| Field | Value | Cardinality | Description |").unwrap();
            writeln!(output, "| --- | --- | --- | --- |").unwrap();
            for field in block.body.fields {
                writeln!(
                    output,
                    "| {} | {} | {} | {} |",
                    inline_code(field.keyword),
                    markdown_cell(&inline_code(&field.value.to_string())),
                    cardinality(field.cardinality),
                    markdown_cell(field.summary),
                )
                .unwrap();
            }
            writeln!(output).unwrap();
        }

        render_rules(&mut output, block.rules);
    }

    writeln!(output, "## Global rules\n").unwrap();
    if spec.rules.is_empty() {
        writeln!(output, "No additional global validation rules are defined.\n").unwrap();
    } else {
        render_rules(&mut output, spec.rules);
    }

    if !spec.examples.is_empty() {
        writeln!(output, "## Complete examples\n").unwrap();
        for example in spec.examples {
            let validity = if example.valid { "Valid" } else { "Invalid" };
            writeln!(output, "### {}: {}\n", validity, example.summary).unwrap();
            writeln!(output, "{}", fenced_code("bts", example.source.trim())).unwrap();
        }
    }

    output
}

fn render_rules(output: &mut String, rules: &[RuleDesc]) {
    if rules.is_empty() {
        return;
    }

    writeln!(output, "Rules:").unwrap();
    for rule in rules {
        writeln!(output, "- {}: {}", inline_code(rule.id.as_str()), rule.summary).unwrap();
    }
    writeln!(output).unwrap();
}

fn name_requirement(name: NameDesc) -> &'static str {
    match name {
        NameDesc::Forbidden => "forbidden",
        NameDesc::Optional => "optional",
        NameDesc::Required => "required",
    }
}

fn cardinality(cardinality: Cardinality) -> &'static str {
    match cardinality {
        Cardinality::Optional => "optional",
        Cardinality::Required => "required",
        Cardinality::Repeated => "repeated",
    }
}

fn placements(spec: &Spec, allowed_in: &[Place]) -> String {
    allowed_in
        .iter()
        .map(|place| match *place {
            Place::Root => "document root".to_owned(),
            Place::Block { id } => spec
                .block_by_id(id)
                .map(|block| inline_code(block.keyword))
                .unwrap_or_else(|| inline_code(id.as_str())),
        })
        .collect::<Vec<_>>()
        .join(", ")
}

fn markdown_cell(value: &str) -> String {
    value.replace('|', "\\|").replace('\n', " ")
}

fn inline_code(value: &str) -> String {
    let longest_run = value
        .split(|character| character != '`')
        .map(str::len)
        .max()
        .unwrap_or_default();
    let fence = "`".repeat(longest_run + 1);

    format!("{fence}{value}{fence}")
}

fn fenced_code(language: &str, value: &str) -> String {
    let longest_run = value
        .lines()
        .flat_map(|line| line.split(|character| character != '`'))
        .map(str::len)
        .max()
        .unwrap_or_default();
    let fence = "`".repeat((longest_run + 1).max(3));

    format!("{fence}{language}\n{value}\n{fence}\n")
}

#[cfg(test)]
mod tests {
    use super::*;
    use uuid::Uuid;

    #[test]
    fn skill_command_defaults_to_local_scope() {
        let matches = command()
            .try_get_matches_from(["setup", "skill", "--agent", "codex"])
            .unwrap();
        let (_, matches) = matches.subcommand().unwrap();

        assert_eq!(matches.get_one::<String>("scope").unwrap(), "local");
    }

    #[test]
    fn plural_skill_alias_is_supported() {
        let matches = command()
            .try_get_matches_from(["setup", "skills", "user", "--agent", "claude"])
            .unwrap();
        let (name, matches) = matches.subcommand().unwrap();

        assert_eq!(name, "skill");
        assert_eq!(matches.get_one::<String>("scope").unwrap(), "user");
    }

    #[test]
    fn resolves_agent_skill_directories() {
        let current = Path::new("/work/project");
        let home = Path::new("/home/example");

        assert_eq!(
            skill_dir(Agent::Codex, Scope::Local, current, Some(home), None).unwrap(),
            current.join(".agents/skills/bts")
        );
        assert_eq!(
            skill_dir(Agent::Claude, Scope::Local, current, Some(home), None).unwrap(),
            current.join(".claude/skills/bts")
        );
        assert_eq!(
            skill_dir(Agent::Codex, Scope::User, current, Some(home), None).unwrap(),
            home.join(".agents/skills/bts")
        );
        assert_eq!(
            skill_dir(Agent::Claude, Scope::User, current, Some(home), None).unwrap(),
            home.join(".claude/skills/bts")
        );
        assert_eq!(
            skill_dir(Agent::Claude, Scope::User, current, None, Some(Path::new("/custom/claude")),).unwrap(),
            PathBuf::from("/custom/claude/skills/bts")
        );
    }

    #[cfg(not(windows))]
    #[test]
    fn resolves_codex_global_skill_directory() {
        assert_eq!(
            skill_dir(Agent::Codex, Scope::Global, Path::new("/work"), None, None).unwrap(),
            PathBuf::from("/etc/codex/skills/bts")
        );
    }

    #[test]
    fn rejects_unsupported_claude_global_scope() {
        assert!(matches!(
            skill_dir(Agent::Claude, Scope::Global, Path::new("/work"), None, None),
            Err(SetupError::UnsupportedClaudeGlobal)
        ));
    }

    #[test]
    fn renders_the_language_spec_into_the_skill() {
        let skill = render_skill(&SPEC);

        assert!(skill.starts_with("---\nname: bts\ndescription:"));
        assert!(skill.contains(GENERATED_MARKER));
        assert!(skill.contains("bts generate --from <path> --count <traces> --over <duration> --dry-run"));
        assert!(skill.contains(SPEC.summary));
        assert!(skill.contains(SPEC.surface.grammar.trim()));
        for expression in SPEC.expressions {
            assert!(skill.contains(expression.id.as_str()));
            assert!(skill.contains(expression.syntax));
            assert!(skill.contains(expression.summary));
        }
        for function in SPEC.functions {
            assert!(skill.contains(function.name));
            assert!(skill.contains(function.syntax));
            assert!(skill.contains(function.summary));
        }
        for block in SPEC.blocks {
            assert!(skill.contains(block.keyword));
            assert!(skill.contains(block.syntax));
            assert!(skill.contains(block.summary));
            for field in block.body.fields {
                assert!(skill.contains(field.keyword));
                assert!(skill.contains(field.summary));
            }
        }
        for example in SPEC.examples {
            assert!(skill.contains(example.summary));
            assert!(skill.contains(example.source.trim()));
        }
        for rule in SPEC.rules {
            assert!(skill.contains(rule.id.as_str()));
            assert!(skill.contains(rule.summary));
        }
    }

    #[test]
    fn updates_generated_skills_but_preserves_unmanaged_skills() {
        let root = env::temp_dir().join(format!("bts-setup-test-{}", Uuid::new_v4()));
        let generated = format!("{GENERATED_MARKER}\nfirst");
        let path = write_skill(&root, &generated).unwrap();
        write_skill(&root, &format!("{GENERATED_MARKER}\nsecond")).unwrap();
        assert!(fs::read_to_string(&path).unwrap().ends_with("second"));

        fs::write(&path, "hand written").unwrap();
        assert!(matches!(write_skill(&root, &generated), Err(SetupError::UnmanagedSkill(_))));

        fs::remove_dir_all(root).unwrap();
    }
}
