use super::{Error, Helper, Item, arg_name, escape, float, fn_name, num};
use crate::dsl::{ArrayElem, BinOp, CtxRef, Func, Part, Range, ScorerStep, Template, UnaryOp, Value};
use std::collections::BTreeSet;
use std::fmt::Write;

// precedence, looser binds lower; comparisons are non-associative because
// python chains them, so both operands require strictly tighter code
const COND: u8 = 1;
const OR: u8 = 2;
const AND: u8 = 3;
const NOT: u8 = 4;
const CMP: u8 = 5;
const ADD: u8 = 6;
const MUL: u8 = 7;
const NEG: u8 = 8;
const POSTFIX: u8 = 9;
const ATOM: u8 = 10;

pub(super) fn module(items: &[Item]) -> Result<String, Error> {
    let mut emitter = Emitter::default();
    let mut functions = Vec::with_capacity(items.len());
    for item in items {
        emitter.next_loop = 0;
        let function_name = fn_name(item.slug);
        let name = escape(item.name);

        let mut function = format!(
            "# scorer \"{}\"\ndef {function_name}(output, input=None, expected=None, metadata=None):\n",
            name
        );
        emitter.steps(item.steps, &name, 1, &mut function)?;
        let fallback = emitter.expr(item.score, 0)?;
        writeln!(
            function,
            "    return {{\"name\": \"{name}\", \"score\": {fallback}, \"metadata\": {{}}}}"
        )
        .expect("writing to a string cannot fail");
        functions.push(function);
    }

    let mut source = String::from("# generated by bts; edits will be overwritten\n");
    for import in &emitter.imports {
        writeln!(source, "import {import}").expect("writing to a string cannot fail");
    }
    source.push_str("\n\n");
    let blocks: Vec<&str> = emitter
        .helpers
        .iter()
        .map(|helper| helper_snippet(*helper))
        .chain(functions.iter().map(String::as_str))
        .collect();
    // pep8 keeps two blank lines between top-level definitions
    source.push_str(&blocks.join("\n\n"));
    Ok(source)
}

fn helper_snippet(helper: Helper) -> &'static str {
    match helper {
        // the stdlib covers every other sampler
        Helper::Poisson => {
            "def poisson(mean):\n    # knuth's method; fine for the small means scorers use\n    limit = math.exp(-mean)\n    count = 0\n    product = random.random()\n    while product > limit:\n        count += 1\n        product *= random.random()\n    return count\n"
        }
        Helper::Round => {
            "def round_away_from_zero(value):\n    return (-1 if value < 0 else 1) * math.floor(abs(value) + 0.5)\n"
        }
        _ => unreachable!("python needs no other helper"),
    }
}

#[derive(Default)]
struct Emitter {
    imports: BTreeSet<&'static str>,
    helpers: BTreeSet<Helper>,
    loops: Vec<(String, String)>,
    next_loop: usize,
}

impl Emitter {
    fn steps(&mut self, steps: &[ScorerStep], name: &str, depth: usize, out: &mut String) -> Result<(), Error> {
        let indent = "    ".repeat(depth);
        for step in steps {
            match step {
                ScorerStep::When(when) => {
                    let cond = self.expr(&when.cond, 0)?;
                    writeln!(out, "{indent}if {cond}:").unwrap();
                    self.steps(&when.steps, name, depth + 1, out)?;
                    if let Some(score) = &when.score {
                        let score = self.expr(score, 0)?;
                        writeln!(
                            out,
                            "{indent}    return {{\"name\": \"{name}\", \"score\": {score}, \"metadata\": {{}}}}"
                        )
                        .unwrap();
                    }
                }
                ScorerStep::Repeat { count, steps } => {
                    let value = self.expr(count, 0)?;
                    let id = self.next_loop;
                    self.next_loop += 1;
                    let suffix = if id == 0 { String::new() } else { format!("_{id}") };
                    let count_name = format!("repeat_count{suffix}");
                    let index_name = format!("repeat_index{suffix}");
                    writeln!(out, "{indent}{count_name} = {value}").unwrap();
                    writeln!(
                        out,
                        "{indent}if isinstance({count_name}, bool) or not isinstance({count_name}, int) or {count_name} < 0:"
                    )
                    .unwrap();
                    writeln!(
                        out,
                        "{indent}    raise ValueError(\"repeat count must be a non-negative integer\")"
                    )
                    .unwrap();
                    writeln!(out, "{indent}for {index_name} in range({count_name}):").unwrap();
                    self.loops.push((index_name, count_name));
                    if steps.is_empty() {
                        writeln!(out, "{indent}    pass").unwrap();
                    } else {
                        self.steps(steps, name, depth + 1, out)?;
                    }
                    self.loops.pop();
                }
            }
        }
        Ok(())
    }

    // precedence-aware: parenthesizes only when the child binds looser than
    // its context requires
    fn expr(&mut self, value: &Value, ctx: u8) -> Result<String, Error> {
        let (code, prec) = self.node(value)?;
        Ok(if prec < ctx { format!("({code})") } else { code })
    }

    fn node(&mut self, value: &Value) -> Result<(String, u8), Error> {
        let node = match value {
            Value::Str(text) => (format!("\"{}\"", escape(text)), ATOM),
            Value::Num(number) => (num(number), ATOM),
            Value::Bool(true) => ("True".to_owned(), ATOM),
            Value::Bool(false) => ("False".to_owned(), ATOM),
            Value::Null => ("None".to_owned(), ATOM),
            Value::ArgRef(arg) => (arg_name(*arg).to_owned(), ATOM),
            Value::Template(template) => self.template(template)?,
            Value::Array(array) => {
                let mut items = Vec::with_capacity(array.elem.len());
                for elem in &array.elem {
                    items.push(match elem {
                        ArrayElem::Item(value) => self.expr(value, 0)?,
                        ArrayElem::Spread(value) => format!("*{}", self.expr(value, OR)?),
                    });
                }
                (format!("[{}]", items.join(", ")), ATOM)
            }
            Value::Object(object) => {
                let mut fields = Vec::with_capacity(object.elem.len());
                for field in &object.elem {
                    fields.push(format!("\"{}\": {}", escape(&field.key), self.expr(&field.value, 0)?));
                }
                (format!("{{{}}}", fields.join(", ")), ATOM)
            }
            Value::VarRef(_) => {
                return Err(Error::Unsupported {
                    what: "a variable binding",
                });
            }
            Value::CtxRef(ctx) => match ctx {
                CtxRef::RepeatIndex => (
                    self.loops
                        .last()
                        .ok_or(Error::Unsupported {
                            what: "repeat.index outside repeat",
                        })?
                        .0
                        .clone(),
                    ATOM,
                ),
                CtxRef::RepeatCount => (
                    self.loops
                        .last()
                        .ok_or(Error::Unsupported {
                            what: "repeat.count outside repeat",
                        })?
                        .1
                        .clone(),
                    ATOM,
                ),
                CtxRef::TraceIndex => return Err(Error::Unsupported { what: "trace.index" }),
            },
            Value::BlockRef { .. } => {
                return Err(Error::Unsupported {
                    what: "a block reference",
                });
            }
            Value::Func { func, .. } => self.func(func)?,
            Value::Unary {
                op: UnaryOp::Neg,
                operand,
                ..
            } => (format!("-{}", self.expr(operand, NEG)?), NEG),
            Value::Unary {
                op: UnaryOp::Not,
                operand,
                ..
            } => (format!("not {}", self.expr(operand, NOT)?), NOT),
            Value::Binary { op, lhs, rhs, .. } => {
                // null comparisons read like a person wrote them
                if matches!(op, BinOp::Eq | BinOp::Ne) && (matches!(**lhs, Value::Null) || matches!(**rhs, Value::Null)) {
                    let side = if matches!(**lhs, Value::Null) { rhs } else { lhs };
                    let side = self.expr(side, CMP + 1)?;
                    let test = if *op == BinOp::Eq { "is None" } else { "is not None" };
                    (format!("{side} {test}"), CMP)
                } else {
                    let (token, prec) = match op {
                        BinOp::Add => ("+", ADD),
                        BinOp::Sub => ("-", ADD),
                        BinOp::Mul => ("*", MUL),
                        BinOp::Div => ("/", MUL),
                        BinOp::Rem => ("%", MUL),
                        BinOp::Eq => ("==", CMP),
                        BinOp::Ne => ("!=", CMP),
                        BinOp::Lt => ("<", CMP),
                        BinOp::Le => ("<=", CMP),
                        BinOp::Gt => (">", CMP),
                        BinOp::Ge => (">=", CMP),
                        BinOp::And => ("and", AND),
                        BinOp::Or => ("or", OR),
                    };
                    // comparisons take both sides strictly tighter so python
                    // never chains them; the rest associate left
                    let lhs_ctx = if prec == CMP { CMP + 1 } else { prec };
                    let lhs = self.expr(lhs, lhs_ctx)?;
                    let rhs = self.expr(rhs, prec + 1)?;
                    (format!("{lhs} {token} {rhs}"), prec)
                }
            }
            Value::Cond { cond, then, otherwise } => {
                let then = self.expr(then, OR)?;
                let cond = self.expr(cond, OR)?;
                let otherwise = self.expr(otherwise, COND)?;
                (format!("{then} if {cond} else {otherwise}"), COND)
            }
            Value::Index { target, index, .. } => {
                let target = self.expr(target, POSTFIX)?;
                let index = self.expr(index, 0)?;
                (format!("{target}[{index}]"), POSTFIX)
            }
            Value::Slice { target, start, end, .. } => {
                let target = self.expr(target, POSTFIX)?;
                let start = start.as_deref().map(|bound| self.expr(bound, 0)).transpose()?;
                let end = end.as_deref().map(|bound| self.expr(bound, 0)).transpose()?;
                let slice = format!("{}:{}", start.unwrap_or_default(), end.unwrap_or_default());
                (format!("{target}[{slice}]"), POSTFIX)
            }
        };
        Ok(node)
    }

    fn func(&mut self, func: &Func) -> Result<(String, u8), Error> {
        let node = match func {
            Func::Choice(options) => {
                self.imports.insert("random");
                (format!("random.choice([{}])", self.list(options)?), POSTFIX)
            }
            Func::Range(Range::Int { min, max }) => {
                self.imports.insert("random");
                (format!("random.randint({min}, {max})"), POSTFIX)
            }
            Func::Range(Range::Float { min, max }) => {
                self.imports.insert("random");
                (format!("random.uniform({}, {})", float(*min), float(*max)), POSTFIX)
            }
            Func::Weighted(options) => {
                self.imports.insert("random");
                let mut values = Vec::with_capacity(options.len());
                let mut weights = Vec::with_capacity(options.len());
                for option in options {
                    values.push(self.expr(&option.value, 0)?);
                    weights.push(float(option.weight));
                }
                (
                    format!("random.choices([{}], weights=[{}])[0]", values.join(", "), weights.join(", ")),
                    POSTFIX,
                )
            }
            Func::Normal { mean, stddev } => {
                self.imports.insert("random");
                (format!("random.gauss({}, {})", float(*mean), float(*stddev)), POSTFIX)
            }
            Func::Lognormal { median, sigma } => {
                self.imports.insert("math");
                self.imports.insert("random");
                (
                    format!("random.lognormvariate(math.log({}), {})", float(*median), float(*sigma)),
                    POSTFIX,
                )
            }
            Func::Exponential { mean } => {
                self.imports.insert("random");
                (format!("random.expovariate(1 / {})", float(*mean)), POSTFIX)
            }
            Func::Pareto { min, shape } => {
                self.imports.insert("random");
                (format!("{} * random.paretovariate({})", float(*min), float(*shape)), MUL)
            }
            Func::Beta { alpha, beta } => {
                self.imports.insert("random");
                (format!("random.betavariate({}, {})", float(*alpha), float(*beta)), POSTFIX)
            }
            Func::Poisson { mean } => {
                self.imports.insert("math");
                self.imports.insert("random");
                self.helpers.insert(Helper::Poisson);
                (format!("poisson({})", float(*mean)), POSTFIX)
            }
            Func::Chance { probability } => {
                self.imports.insert("random");
                (format!("random.random() < {}", float(*probability)), CMP)
            }
            Func::Upper { text } => (format!("{}.upper()", self.expr(text, POSTFIX)?), POSTFIX),
            Func::Lower { text } => (format!("{}.lower()", self.expr(text, POSTFIX)?), POSTFIX),
            Func::Trim { text } => (format!("{}.strip()", self.expr(text, POSTFIX)?), POSTFIX),
            Func::Replace { text, from, to } => {
                let text = self.expr(text, POSTFIX)?;
                let from = self.expr(from, 0)?;
                let to = self.expr(to, 0)?;
                (format!("{text}.replace({from}, {to})"), POSTFIX)
            }
            Func::Split { text, separator } => {
                let text = self.expr(text, POSTFIX)?;
                let separator = self.expr(separator, 0)?;
                (format!("{text}.split({separator})"), POSTFIX)
            }
            Func::Join { array, separator } => {
                let separator = self.expr(separator, POSTFIX)?;
                let array = self.expr(array, 0)?;
                (format!("{separator}.join({array})"), POSTFIX)
            }
            Func::Contains { target, needle } => {
                let needle = self.expr(needle, CMP + 1)?;
                let target = self.expr(target, CMP + 1)?;
                (format!("{needle} in {target}"), CMP)
            }
            Func::StartsWith { text, prefix } => {
                let text = self.expr(text, POSTFIX)?;
                let prefix = self.expr(prefix, 0)?;
                (format!("{text}.startswith({prefix})"), POSTFIX)
            }
            Func::EndsWith { text, suffix } => {
                let text = self.expr(text, POSTFIX)?;
                let suffix = self.expr(suffix, 0)?;
                (format!("{text}.endswith({suffix})"), POSTFIX)
            }
            Func::Len { target } => (format!("len({})", self.expr(target, 0)?), POSTFIX),
            Func::Format { pieces, args } => {
                // format is a template with the pieces as its literals
                let mut parts = Vec::with_capacity(pieces.len() + args.len());
                for (index, piece) in pieces.iter().enumerate() {
                    if !piece.is_empty() {
                        parts.push(Rendered::Lit(piece.clone()));
                    }
                    if let Some(arg) = args.get(index) {
                        parts.push(Rendered::Expr(self.expr(arg, 0)?));
                    }
                }
                interpolate(parts)
            }
            Func::Clamp { value, min, max } => {
                let min = self.expr(min, 0)?;
                let max = self.expr(max, 0)?;
                let value = self.expr(value, 0)?;
                (format!("max({min}, min({max}, {value}))"), POSTFIX)
            }
            Func::Round { value } => {
                self.imports.insert("math");
                self.helpers.insert(Helper::Round);
                (format!("round_away_from_zero({})", self.expr(value, 0)?), POSTFIX)
            }
            Func::Floor { value } => {
                self.imports.insert("math");
                (format!("math.floor({})", self.expr(value, 0)?), POSTFIX)
            }
            Func::Ceil { value } => {
                self.imports.insert("math");
                (format!("math.ceil({})", self.expr(value, 0)?), POSTFIX)
            }
            Func::Abs { value } => (format!("abs({})", self.expr(value, 0)?), POSTFIX),
            Func::Min(options) => (format!("min({})", self.list(options)?), POSTFIX),
            Func::Max(options) => (format!("max({})", self.list(options)?), POSTFIX),
            Func::Uuid => {
                self.imports.insert("uuid");
                ("str(uuid.uuid4())".to_owned(), POSTFIX)
            }
            Func::Hex { length } => {
                self.imports.insert("random");
                (
                    format!("\"\".join(random.choices(\"0123456789abcdef\", k={length}))"),
                    POSTFIX,
                )
            }
            Func::Alphanum { length } => {
                self.imports.insert("random");
                self.imports.insert("string");
                (
                    format!("\"\".join(random.choices(string.ascii_letters + string.digits, k={length}))"),
                    POSTFIX,
                )
            }
            Func::Tokens { .. } => return Err(Error::Unsupported { what: "`tokens`" }),
            Func::Noise { .. } => return Err(Error::Unsupported { what: "`noise`" }),
        };
        Ok(node)
    }

    fn list(&mut self, values: &[Value]) -> Result<String, Error> {
        let mut items = Vec::with_capacity(values.len());
        for value in values {
            items.push(self.expr(value, 0)?);
        }
        Ok(items.join(", "))
    }

    fn template(&mut self, template: &Template) -> Result<(String, u8), Error> {
        let mut parts = Vec::with_capacity(template.parts.len());
        for part in &template.parts {
            match part {
                Part::Lit(text) => parts.push(Rendered::Lit(text.clone())),
                Part::Dynamic(value) => parts.push(Rendered::Expr(self.expr(value, 0)?)),
                Part::Ref(_) | Part::VarRef(_) => {
                    return Err(Error::Unsupported {
                        what: "a context reference",
                    });
                }
            }
        }
        Ok(interpolate(parts))
    }
}

enum Rendered {
    Lit(String),
    Expr(String),
}

// an f-string when every hole stays quote- and backslash-free (older runtimes
// reject them inside holes), plain concatenation otherwise
fn interpolate(parts: Vec<Rendered>) -> (String, u8) {
    let simple = parts.iter().all(|part| match part {
        Rendered::Expr(code) => !code.contains('"') && !code.contains('\\'),
        Rendered::Lit(_) => true,
    });

    if simple {
        let mut out = String::from("f\"");
        for part in parts {
            match part {
                Rendered::Lit(text) => out.push_str(&escape(&text).replace('{', "{{").replace('}', "}}")),
                Rendered::Expr(code) => {
                    out.push('{');
                    out.push_str(&code);
                    out.push('}');
                }
            }
        }
        out.push('"');
        (out, ATOM)
    } else {
        let pieces: Vec<String> = parts
            .into_iter()
            .map(|part| match part {
                Rendered::Lit(text) => format!("\"{}\"", escape(&text)),
                Rendered::Expr(code) => format!("str({code})"),
            })
            .collect();
        (pieces.join(" + "), ADD)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::dsl::{Scorer, ScorerKind, compile};

    fn render(source: &str) -> Result<String, Error> {
        let model = compile(source).unwrap();
        let named: Vec<(String, &Scorer)> = model
            .scorers
            .iter()
            .map(|scorer| (crate::scg::component::slugify(&scorer.name).unwrap(), scorer))
            .collect();
        let items: Vec<Item> = named
            .iter()
            .map(|(slug, scorer)| {
                let ScorerKind::Code { score, steps } = &scorer.kind else {
                    panic!("expected a code scorer");
                };
                Item {
                    name: &scorer.name,
                    slug,
                    score,
                    steps,
                }
            })
            .collect();
        module(&items)
    }

    fn emit(source: &str) -> String {
        render(source).unwrap()
    }

    #[test]
    fn emits_nested_scorer_repeats() {
        let generated = emit(
            r#"scorer "s" { code {
            score = 0
            repeat {
                count = len(output)
                when { cond = output[repeat.index] == expected score = 1 }
                repeat { count = repeat.index + 1 when { cond = repeat.index < repeat.count score = 0.5 } }
            }
        } }"#,
        );
        assert!(generated.contains("repeat_count = len(output)"));
        assert!(generated.contains("for repeat_index in range(repeat_count):"));
        assert!(generated.contains("if output[repeat_index] == expected:"));
        assert!(generated.contains("repeat_count_1 = repeat_index + 1"));
        assert!(generated.contains("if repeat_index_1 < repeat_count_1:"));
    }

    #[test]
    fn emits_nested_when_fallthrough() {
        let generated = emit(
            r#"scorer "s" { code {
            score = 0
            when { cond = len(output) > 0
                when { cond = output[0] == expected score = 1 }
                score = 0.5
            }
        } }"#,
        );
        assert!(generated.contains("    if len(output) > 0:\n        if output[0] == expected:\n            return"));
        assert!(generated.contains("\n        return {\"name\": \"s\", \"score\": 0.5"));
        assert!(generated.contains("\n    return {\"name\": \"s\", \"score\": 0"));
    }

    // the expression under test, wrapped in a minimal scorer
    fn emit_score(expr: &str) -> String {
        let generated = emit(&format!(r#"scorer "s" {{ code {{ score = {expr} }} }}"#));
        let line = generated.lines().rev().find(|line| !line.is_empty()).unwrap();
        line.trim_start()
            .strip_prefix("return {\"name\": \"s\", \"score\": ")
            .unwrap()
            .strip_suffix(", \"metadata\": {}}")
            .unwrap()
            .to_owned()
    }

    #[test]
    fn packs_the_canonical_scorers_into_one_module() {
        let generated = emit(include_str!("../../../examples/code_scorer.bt"));
        assert_eq!(
            generated,
            r#"# generated by bts; edits will be overwritten
import random


# scorer "response-quality"
def scorer_response_quality(output, input=None, expected=None, metadata=None):
    if output is None:
        return {"name": "response-quality", "score": 0, "metadata": {}}
    if "I'm sorry" in output:
        return {"name": "response-quality", "score": random.uniform(0.1, 0.4), "metadata": {}}
    return {"name": "response-quality", "score": max(0, min(1, random.gauss(0.78, 0.12))), "metadata": {}}


# scorer "response-length"
def scorer_response_length(output, input=None, expected=None, metadata=None):
    if output is None:
        return {"name": "response-length", "score": 0, "metadata": {}}
    return {"name": "response-length", "score": max(0.1, min(0.9, len(output) / 400)), "metadata": {}}
"#
        );
    }

    #[test]
    fn derives_function_names_from_slugs() {
        assert_eq!(fn_name("response-quality"), "scorer_response_quality");
        assert_eq!(fn_name("2fast"), "scorer_2fast");
    }

    #[test]
    fn prefixes_language_keywords_and_runtime_names() {
        for name in ["class", "poisson", "random", "handler", "len"] {
            let generated = emit(&format!(r#"scorer "{name}" {{ code {{ score = 0.5 }} }}"#));
            assert!(generated.contains(&format!("def scorer_{name}(")), "name {name}");
        }
    }

    #[test]
    fn rounds_dynamic_scores_away_from_zero() {
        let generated = emit(r#"scorer "s" { code { score = round(output) } }"#);
        assert!(generated.contains("import math\n"));
        assert!(
            generated.contains(
                "def round_away_from_zero(value):\n    return (-1 if value < 0 else 1) * math.floor(abs(value) + 0.5)"
            )
        );
        assert!(generated.contains("\"score\": round_away_from_zero(output)"));
    }

    #[test]
    fn parenthesizes_only_when_precedence_demands() {
        // constant arithmetic folds away, so operands must stay dynamic
        assert_eq!(emit_score("len(output) + len(input) * 2"), "len(output) + len(input) * 2");
        assert_eq!(emit_score("(len(output) + len(input)) % 2"), "(len(output) + len(input)) % 2");
        assert_eq!(emit_score("len(output) > 5 ? 0.1 : 0.9"), "0.1 if len(output) > 5 else 0.9");
    }

    #[test]
    fn never_chains_python_comparisons() {
        let generated =
            emit(r#"scorer "s" { code { score = 0.5 when { cond = (len(output) > 1) == (len(input) > 1) score = 0 } } }"#);
        assert!(
            generated.contains("if (len(output) > 1) == (len(input) > 1):"),
            "generated:\n{generated}"
        );
    }

    #[test]
    fn escapes_string_literals() {
        // the dsl has no backslash escapes, so probe the emitter directly
        let mut emitter = Emitter::default();
        let rendered = emitter.expr(&Value::Str("say \"hi\"\n\t\\".to_owned()), 0).unwrap();
        assert_eq!(rendered, r#""say \"hi\"\n\t\\""#);
    }

    #[test]
    fn shares_stdlib_random_import_across_scorers() {
        let generated = emit(
            r#"
            scorer "first" { code { score = clamp(normal(0.5, 0.1) + range(0.1, 0.2), 0, 1) } }
            scorer "second" { code { score = clamp(normal(0.2, 0.1) + range(0.2, 0.3), 0, 1) } }
            "#,
        );
        assert_eq!(generated.matches("import random").count(), 1);
        assert_eq!(generated.matches("random.gauss(").count(), 2);
        assert_eq!(generated.matches("random.uniform(").count(), 2);
        let import_at = generated.find("import random").unwrap();
        let first_at = generated.find("def scorer_first").unwrap();
        let second_at = generated.find("def scorer_second").unwrap();
        assert!(import_at < first_at && first_at < second_at);
    }

    #[test]
    fn emits_stdlib_integer_and_float_ranges() {
        let integer = emit_score("range(1, 3)");
        let float = emit_score("range(0.1, 0.4)");
        assert_eq!(integer, "random.randint(1, 3)");
        assert_eq!(float, "random.uniform(0.1, 0.4)");
    }

    #[test]
    fn interpolates_templates_as_f_strings() {
        // a quote-free hole makes an f-string
        let generated = emit(r#"scorer "s" { code { score = 0.5 when { cond = "${output}!" == "pro!" score = 1 } } }"#);
        assert!(generated.contains(r#"if f"{output}!" == "pro!":"#), "generated:\n{generated}");

        // a hole whose rendering needs quotes falls back to concatenation
        let generated = emit(r#"scorer "s" { code { score = 0.5 when { cond = "${metadata.tier}!" == "pro!" score = 1 } } }"#);
        assert!(
            generated.contains(r#"if str(metadata["tier"]) + "!" == "pro!":"#),
            "generated:\n{generated}"
        );
    }

    #[test]
    fn refuses_untranspilable_values() {
        // hand-built: the modeler never lets these through
        let mut emitter = Emitter::default();
        assert!(matches!(
            emitter.expr(&Value::VarRef("x".to_owned()), 0),
            Err(Error::Unsupported { .. })
        ));
    }
}
