use super::{Error, Helper, Item, arg_name, escape, float, fn_name, num};
use crate::dsl::{ArrayElem, BinOp, Func, Part, Range, Template, UnaryOp, Value};
use std::collections::BTreeSet;
use std::fmt::Write;

// precedence, looser binds lower
const COND: u8 = 1;
const OR: u8 = 2;
const AND: u8 = 3;
const EQ: u8 = 4;
const REL: u8 = 5;
const ADD: u8 = 6;
const MUL: u8 = 7;
const UNARY: u8 = 8;
const POSTFIX: u8 = 9;
const ATOM: u8 = 10;

pub(super) fn module(items: &[Item]) -> Result<String, Error> {
    let mut emitter = Emitter::default();
    let mut functions = Vec::with_capacity(items.len());
    for item in items {
        let function_name = fn_name(item.slug);
        let name = escape(item.name);

        let mut function = format!(
            "// scorer \"{}\"\nfunction {function_name}({{ input, output, expected, metadata }}: {{ input?: any; output: any; expected?: any; metadata?: any }}): {{ name: string; score: number; metadata: Record<string, unknown> }} {{\n",
            name
        );
        for when in item.whens {
            let cond = emitter.expr(&when.cond, 0)?;
            let score = emitter.expr(&when.score, 0)?;
            writeln!(function, "  if ({cond}) {{").expect("writing to a string cannot fail");
            writeln!(function, "    return {{ name: \"{name}\", score: {score}, metadata: {{}} }};")
                .expect("writing to a string cannot fail");
            function.push_str("  }\n");
        }
        let fallback = emitter.expr(item.score, 0)?;
        writeln!(
            function,
            "  return {{ name: \"{name}\", score: {fallback}, metadata: {{}} }};"
        )
        .expect("writing to a string cannot fail");
        function.push_str("}\n");
        functions.push(function);
    }

    let mut source = String::from("// generated by bts; edits will be overwritten\n");
    for helper in &emitter.helpers {
        source.push('\n');
        source.push_str(helper_snippet(*helper));
    }
    for function in &functions {
        source.push('\n');
        source.push_str(function);
    }
    Ok(source)
}

fn helper_snippet(helper: Helper) -> &'static str {
    match helper {
        Helper::Normal => {
            "// standard normal via box-muller, scaled to the requested distribution\nfunction normal(mean: number, stddev: number): number {\n  let u = 0;\n  let v = 0;\n  while (u === 0) u = Math.random();\n  while (v === 0) v = Math.random();\n  return mean + stddev * Math.sqrt(-2 * Math.log(u)) * Math.cos(2 * Math.PI * v);\n}\n"
        }
        Helper::Gamma => {
            "// marsaglia-tsang, with the sub-1 shape boosted from shape + 1\nfunction gamma(shape: number): number {\n  if (shape < 1) return gamma(shape + 1) * Math.pow(Math.random(), 1 / shape);\n  const d = shape - 1 / 3;\n  const c = 1 / Math.sqrt(9 * d);\n  for (;;) {\n    const x = normal(0, 1);\n    const v = Math.pow(1 + c * x, 3);\n    if (v <= 0) continue;\n    const u = Math.random();\n    if (u < 1 - 0.0331 * Math.pow(x, 4) || Math.log(u) < 0.5 * x * x + d * (1 - v + Math.log(v))) {\n      return d * v;\n    }\n  }\n}\n"
        }
        Helper::Lognormal => {
            "function lognormal(median: number, sigma: number): number {\n  return median * Math.exp(sigma * normal(0, 1));\n}\n"
        }
        Helper::Exponential => {
            "function exponential(mean: number): number {\n  return -mean * Math.log(1 - Math.random());\n}\n"
        }
        Helper::Pareto => {
            "function pareto(min: number, shape: number): number {\n  return min / Math.pow(1 - Math.random(), 1 / shape);\n}\n"
        }
        Helper::Beta => {
            "function beta(alpha: number, betaShape: number): number {\n  const a = gamma(alpha);\n  const b = gamma(betaShape);\n  return a / (a + b);\n}\n"
        }
        Helper::Poisson => {
            "// knuth's method; fine for the small means scorers use\nfunction poisson(mean: number): number {\n  const limit = Math.exp(-mean);\n  let count = 0;\n  let product = Math.random();\n  while (product > limit) {\n    count += 1;\n    product *= Math.random();\n  }\n  return count;\n}\n"
        }
        Helper::Choice => {
            "function choice<T>(options: T[]): T {\n  return options[Math.floor(Math.random() * options.length)];\n}\n"
        }
        Helper::Weighted => {
            "function weighted<T>(options: [T, number][]): T {\n  let total = 0;\n  for (const [, weight] of options) total += weight;\n  let roll = Math.random() * total;\n  for (const [value, weight] of options) {\n    roll -= weight;\n    if (roll <= 0) return value;\n  }\n  return options[options.length - 1][0];\n}\n"
        }
        Helper::RandInt => {
            "function randomInt(min: number, max: number): number {\n  return Math.floor(Math.random() * (max - min + 1)) + min;\n}\n"
        }
        Helper::Hex => {
            "function randomHex(length: number): string {\n  let result = \"\";\n  for (let i = 0; i < length; i += 1) result += \"0123456789abcdef\"[Math.floor(Math.random() * 16)];\n  return result;\n}\n"
        }
        Helper::Alphanum => {
            "function randomAlphanum(length: number): string {\n  const pool = \"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz\";\n  let result = \"\";\n  for (let i = 0; i < length; i += 1) result += pool[Math.floor(Math.random() * pool.length)];\n  return result;\n}\n"
        }
        Helper::Round => {
            "function roundAwayFromZero(value: number): number {\n  return (value < 0 ? -1 : 1) * Math.floor(Math.abs(value) + 0.5);\n}\n"
        }
    }
}

#[derive(Default)]
struct Emitter {
    helpers: BTreeSet<Helper>,
}

impl Emitter {
    // some helpers call others; pulling one in pulls its dependencies
    fn need(&mut self, helper: Helper) {
        match helper {
            Helper::Lognormal => self.need(Helper::Normal),
            Helper::Beta => self.need(Helper::Gamma),
            Helper::Gamma => self.need(Helper::Normal),
            _ => {}
        }
        self.helpers.insert(helper);
    }

    // precedence-aware: parenthesizes only when the child binds looser than
    // its context requires
    fn expr(&mut self, value: &Value, ctx: u8) -> Result<String, Error> {
        let (code, prec) = self.node(value)?;
        Ok(if prec < ctx { format!("({code})") } else { code })
    }

    fn node(&mut self, value: &Value) -> Result<(String, u8), Error> {
        let node = match value {
            Value::Str(text) => (format!("\"{}\"", escape(text)), ATOM),
            Value::Num(number) => (num(number), ATOM),
            Value::Bool(true) => ("true".to_owned(), ATOM),
            Value::Bool(false) => ("false".to_owned(), ATOM),
            Value::Null => ("null".to_owned(), ATOM),
            Value::ArgRef(arg) => (arg_name(*arg).to_owned(), ATOM),
            Value::Template(template) => (self.template(template)?, ATOM),
            Value::Array(array) => {
                let mut items = Vec::with_capacity(array.elem.len());
                for elem in &array.elem {
                    items.push(match elem {
                        ArrayElem::Item(value) => self.expr(value, 0)?,
                        ArrayElem::Spread(value) => format!("...{}", self.expr(value, 0)?),
                    });
                }
                (format!("[{}]", items.join(", ")), ATOM)
            }
            Value::Object(object) => {
                let mut fields = Vec::with_capacity(object.elem.len());
                for field in &object.elem {
                    let key = if is_identifier(&field.key) {
                        field.key.clone()
                    } else {
                        format!("\"{}\"", escape(&field.key))
                    };
                    fields.push(format!("{key}: {}", self.expr(&field.value, 0)?));
                }
                (format!("{{ {} }}", fields.join(", ")), ATOM)
            }
            Value::VarRef(_) => {
                return Err(Error::Unsupported {
                    what: "a variable binding",
                });
            }
            Value::CtxRef(_) => {
                return Err(Error::Unsupported {
                    what: "a context reference",
                });
            }
            Value::BlockRef { .. } => {
                return Err(Error::Unsupported {
                    what: "a block reference",
                });
            }
            Value::Func { func, .. } => self.func(func)?,
            Value::Unary {
                op: UnaryOp::Neg,
                operand,
                ..
            } => (format!("-{}", self.expr(operand, UNARY)?), UNARY),
            Value::Unary {
                op: UnaryOp::Not,
                operand,
                ..
            } => (format!("!{}", self.expr(operand, UNARY)?), UNARY),
            Value::Binary { op, lhs, rhs, .. } => {
                // loose null tests catch braintrust passing undefined too
                if matches!(op, BinOp::Eq | BinOp::Ne) && (matches!(**lhs, Value::Null) || matches!(**rhs, Value::Null)) {
                    let side = if matches!(**lhs, Value::Null) { rhs } else { lhs };
                    let side = self.expr(side, EQ)?;
                    let token = if *op == BinOp::Eq { "==" } else { "!=" };
                    (format!("{side} {token} null"), EQ)
                } else {
                    let (token, prec) = match op {
                        BinOp::Add => ("+", ADD),
                        BinOp::Sub => ("-", ADD),
                        BinOp::Mul => ("*", MUL),
                        BinOp::Div => ("/", MUL),
                        BinOp::Rem => ("%", MUL),
                        BinOp::Eq => ("===", EQ),
                        BinOp::Ne => ("!==", EQ),
                        BinOp::Lt => ("<", REL),
                        BinOp::Le => ("<=", REL),
                        BinOp::Gt => (">", REL),
                        BinOp::Ge => (">=", REL),
                        BinOp::And => ("&&", AND),
                        BinOp::Or => ("||", OR),
                    };
                    let lhs = self.expr(lhs, prec)?;
                    let rhs = self.expr(rhs, prec + 1)?;
                    (format!("{lhs} {token} {rhs}"), prec)
                }
            }
            Value::Cond { cond, then, otherwise } => {
                let cond = self.expr(cond, OR)?;
                let then = self.expr(then, COND)?;
                let otherwise = self.expr(otherwise, COND)?;
                (format!("{cond} ? {then} : {otherwise}"), COND)
            }
            Value::Index { target, index, .. } => {
                let target = self.expr(target, POSTFIX)?;
                match &**index {
                    Value::Str(key) if is_identifier(key) => (format!("{target}.{key}"), POSTFIX),
                    index => {
                        let index = self.expr(index, 0)?;
                        (format!("{target}[{index}]"), POSTFIX)
                    }
                }
            }
            Value::Slice { target, start, end, .. } => {
                let target = self.expr(target, POSTFIX)?;
                let start = match start {
                    Some(bound) => self.expr(bound, 0)?,
                    None => "0".to_owned(),
                };
                let slice = match end {
                    Some(bound) => format!("{start}, {}", self.expr(bound, 0)?),
                    None => start,
                };
                (format!("{target}.slice({slice})"), POSTFIX)
            }
        };
        Ok(node)
    }

    fn func(&mut self, func: &Func) -> Result<(String, u8), Error> {
        let node = match func {
            Func::Choice(options) => {
                self.need(Helper::Choice);
                (format!("choice([{}])", self.list(options)?), POSTFIX)
            }
            Func::Range(Range::Int { min, max }) => {
                self.need(Helper::RandInt);
                (format!("randomInt({min}, {max})"), POSTFIX)
            }
            Func::Range(Range::Float { min, max }) => (
                format!("{} + Math.random() * ({} - {})", float(*min), float(*max), float(*min)),
                ADD,
            ),
            Func::Weighted(options) => {
                self.need(Helper::Weighted);
                let mut pairs = Vec::with_capacity(options.len());
                for option in options {
                    pairs.push(format!("[{}, {}]", self.expr(&option.value, 0)?, float(option.weight)));
                }
                (format!("weighted([{}])", pairs.join(", ")), POSTFIX)
            }
            Func::Normal { mean, stddev } => {
                self.need(Helper::Normal);
                (format!("normal({}, {})", float(*mean), float(*stddev)), POSTFIX)
            }
            Func::Lognormal { median, sigma } => {
                self.need(Helper::Lognormal);
                (format!("lognormal({}, {})", float(*median), float(*sigma)), POSTFIX)
            }
            Func::Exponential { mean } => {
                self.need(Helper::Exponential);
                (format!("exponential({})", float(*mean)), POSTFIX)
            }
            Func::Pareto { min, shape } => {
                self.need(Helper::Pareto);
                (format!("pareto({}, {})", float(*min), float(*shape)), POSTFIX)
            }
            Func::Beta { alpha, beta } => {
                self.need(Helper::Beta);
                (format!("beta({}, {})", float(*alpha), float(*beta)), POSTFIX)
            }
            Func::Poisson { mean } => {
                self.need(Helper::Poisson);
                (format!("poisson({})", float(*mean)), POSTFIX)
            }
            Func::Chance { probability } => (format!("Math.random() < {}", float(*probability)), REL),
            Func::Upper { text } => (format!("{}.toUpperCase()", self.expr(text, POSTFIX)?), POSTFIX),
            Func::Lower { text } => (format!("{}.toLowerCase()", self.expr(text, POSTFIX)?), POSTFIX),
            Func::Trim { text } => (format!("{}.trim()", self.expr(text, POSTFIX)?), POSTFIX),
            Func::Replace { text, from, to } => {
                let text = self.expr(text, POSTFIX)?;
                let from = self.expr(from, 0)?;
                let to = self.expr(to, 0)?;
                (format!("{text}.replaceAll({from}, {to})"), POSTFIX)
            }
            Func::Split { text, separator } => {
                let text = self.expr(text, POSTFIX)?;
                let separator = self.expr(separator, 0)?;
                (format!("{text}.split({separator})"), POSTFIX)
            }
            Func::Join { array, separator } => {
                let array = self.expr(array, POSTFIX)?;
                let separator = self.expr(separator, 0)?;
                (format!("{array}.join({separator})"), POSTFIX)
            }
            Func::Contains { target, needle } => {
                let target = self.expr(target, POSTFIX)?;
                let needle = self.expr(needle, 0)?;
                (format!("{target}.includes({needle})"), POSTFIX)
            }
            Func::StartsWith { text, prefix } => {
                let text = self.expr(text, POSTFIX)?;
                let prefix = self.expr(prefix, 0)?;
                (format!("{text}.startsWith({prefix})"), POSTFIX)
            }
            Func::EndsWith { text, suffix } => {
                let text = self.expr(text, POSTFIX)?;
                let suffix = self.expr(suffix, 0)?;
                (format!("{text}.endsWith({suffix})"), POSTFIX)
            }
            Func::Len { target } => (format!("{}.length", self.expr(target, POSTFIX)?), POSTFIX),
            Func::Format { pieces, args } => {
                let mut parts = Vec::with_capacity(pieces.len() + args.len());
                for (index, piece) in pieces.iter().enumerate() {
                    if !piece.is_empty() {
                        parts.push(Rendered::Lit(piece.clone()));
                    }
                    if let Some(arg) = args.get(index) {
                        parts.push(Rendered::Expr(self.expr(arg, 0)?));
                    }
                }
                (literal(parts), ATOM)
            }
            Func::Clamp { value, min, max } => {
                let min = self.expr(min, 0)?;
                let max = self.expr(max, 0)?;
                let value = self.expr(value, 0)?;
                (format!("Math.max({min}, Math.min({max}, {value}))"), POSTFIX)
            }
            Func::Round { value } => {
                self.need(Helper::Round);
                (format!("roundAwayFromZero({})", self.expr(value, 0)?), POSTFIX)
            }
            Func::Floor { value } => (format!("Math.floor({})", self.expr(value, 0)?), POSTFIX),
            Func::Ceil { value } => (format!("Math.ceil({})", self.expr(value, 0)?), POSTFIX),
            Func::Abs { value } => (format!("Math.abs({})", self.expr(value, 0)?), POSTFIX),
            Func::Min(options) => (format!("Math.min({})", self.list(options)?), POSTFIX),
            Func::Max(options) => (format!("Math.max({})", self.list(options)?), POSTFIX),
            Func::Uuid => ("crypto.randomUUID()".to_owned(), POSTFIX),
            Func::Hex { length } => {
                self.need(Helper::Hex);
                (format!("randomHex({length})"), POSTFIX)
            }
            Func::Alphanum { length } => {
                self.need(Helper::Alphanum);
                (format!("randomAlphanum({length})"), POSTFIX)
            }
            Func::Tokens { .. } => return Err(Error::Unsupported { what: "`tokens`" }),
            Func::Noise { .. } => return Err(Error::Unsupported { what: "`noise`" }),
        };
        Ok(node)
    }

    fn list(&mut self, values: &[Value]) -> Result<String, Error> {
        let mut items = Vec::with_capacity(values.len());
        for value in values {
            items.push(self.expr(value, 0)?);
        }
        Ok(items.join(", "))
    }

    fn template(&mut self, template: &Template) -> Result<String, Error> {
        let mut parts = Vec::with_capacity(template.parts.len());
        for part in &template.parts {
            match part {
                Part::Lit(text) => parts.push(Rendered::Lit(text.clone())),
                Part::Dynamic(value) => parts.push(Rendered::Expr(self.expr(value, 0)?)),
                Part::Ref(_) | Part::VarRef(_) => {
                    return Err(Error::Unsupported {
                        what: "a context reference",
                    });
                }
            }
        }
        Ok(literal(parts))
    }
}

enum Rendered {
    Lit(String),
    Expr(String),
}

// a template literal; holes take any expression, so no fallback is needed
fn literal(parts: Vec<Rendered>) -> String {
    let mut out = String::from("`");
    for part in parts {
        match part {
            Rendered::Lit(text) => {
                out.push_str(&text.replace('\\', "\\\\").replace('`', "\\`").replace("${", "\\${"));
            }
            Rendered::Expr(code) => {
                out.push_str("${");
                out.push_str(&code);
                out.push('}');
            }
        }
    }
    out.push('`');
    out
}

fn is_identifier(key: &str) -> bool {
    !key.is_empty()
        && key
            .chars()
            .next()
            .is_some_and(|first| first.is_ascii_alphabetic() || first == '_')
        && key.chars().all(|part| part.is_ascii_alphanumeric() || part == '_')
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::dsl::{Scorer, ScorerKind, compile};

    fn render(source: &str) -> Result<String, Error> {
        let model = compile(source).unwrap();
        let named: Vec<(String, &Scorer)> = model
            .scorers
            .iter()
            .map(|scorer| (crate::scg::component::slugify(&scorer.name).unwrap(), scorer))
            .collect();
        let items: Vec<Item> = named
            .iter()
            .map(|(slug, scorer)| {
                let ScorerKind::Code { score, whens } = &scorer.kind else {
                    panic!("expected a code scorer");
                };
                Item {
                    name: &scorer.name,
                    slug,
                    score,
                    whens,
                }
            })
            .collect();
        module(&items)
    }

    fn emit(source: &str) -> String {
        render(source).unwrap()
    }

    #[test]
    fn packs_the_canonical_scorers_into_one_module() {
        let generated = emit(include_str!("../../../examples/code_scorer.bt"));
        assert_eq!(
            generated,
            r#"// generated by bts; edits will be overwritten

// standard normal via box-muller, scaled to the requested distribution
function normal(mean: number, stddev: number): number {
  let u = 0;
  let v = 0;
  while (u === 0) u = Math.random();
  while (v === 0) v = Math.random();
  return mean + stddev * Math.sqrt(-2 * Math.log(u)) * Math.cos(2 * Math.PI * v);
}

// scorer "response-quality"
function scorer_response_quality({ input, output, expected, metadata }: { input?: any; output: any; expected?: any; metadata?: any }): { name: string; score: number; metadata: Record<string, unknown> } {
  if (output == null) {
    return { name: "response-quality", score: 0, metadata: {} };
  }
  if (output.includes("I'm sorry")) {
    return { name: "response-quality", score: 0.1 + Math.random() * (0.4 - 0.1), metadata: {} };
  }
  return { name: "response-quality", score: Math.max(0, Math.min(1, normal(0.78, 0.12))), metadata: {} };
}

// scorer "response-length"
function scorer_response_length({ input, output, expected, metadata }: { input?: any; output: any; expected?: any; metadata?: any }): { name: string; score: number; metadata: Record<string, unknown> } {
  if (output == null) {
    return { name: "response-length", score: 0, metadata: {} };
  }
  return { name: "response-length", score: Math.max(0.1, Math.min(0.9, output.length / 400)), metadata: {} };
}
"#
        );
    }

    #[test]
    fn derives_function_names_from_slugs() {
        assert_eq!(fn_name("response-quality"), "scorer_response_quality");
        assert_eq!(fn_name("a-b-c"), "scorer_a_b_c");
        assert_eq!(fn_name("2fast-2furious"), "scorer_2fast_2furious");
        assert_ne!(fn_name("a-1"), fn_name("a1"));
    }

    #[test]
    fn prefixes_language_keywords_and_runtime_names() {
        for name in ["default", "normal", "weighted", "handler", "crypto"] {
            let generated = emit(&format!(r#"scorer "{name}" {{ code {{ score = 0.5 }} }}"#));
            assert!(generated.contains(&format!("function scorer_{name}(")), "name {name}");
        }
    }

    #[test]
    fn packed_scorers_with_distinct_slugs_keep_distinct_function_names() {
        let generated = emit(
            r#"scorer "a-1" { file = "shared" code { score = 0.5 } }
               scorer "a1" { file = "shared" code { score = 0.6 } }"#,
        );
        assert!(generated.contains("function scorer_a_1("));
        assert!(generated.contains("function scorer_a1("));
    }

    #[test]
    fn rounds_dynamic_scores_away_from_zero() {
        let generated = emit(r#"scorer "s" { code { score = round(output) } }"#);
        assert!(generated.contains(
            "function roundAwayFromZero(value: number): number {\n  return (value < 0 ? -1 : 1) * Math.floor(Math.abs(value) + 0.5);"
        ));
        assert!(generated.contains("score: roundAwayFromZero(output), metadata: {}"));
    }

    #[test]
    fn pulls_helper_dependencies_in_declaration_order() {
        let generated = emit(r#"scorer "s" { code { score = clamp(lognormal(0.5, 0.2), 0, 1) } }"#);
        let normal_at = generated.find("function normal(").unwrap();
        let lognormal_at = generated.find("function lognormal(").unwrap();
        let scorer_at = generated.find("function scorer_s(").unwrap();
        assert!(normal_at < lognormal_at && lognormal_at < scorer_at);
    }

    #[test]
    fn dots_identifier_keys_and_brackets_the_rest() {
        let generated =
            emit(r#"scorer "s" { code { score = 0.5 when { cond = metadata.tier == metadata["user tier"] score = 0 } } }"#);
        assert!(
            generated.contains(r#"if (metadata.tier === metadata["user tier"]) {"#),
            "generated:\n{generated}"
        );
    }

    #[test]
    fn escapes_template_literals() {
        let generated = emit(
            r#"scorer "s" { code { score = 0.5 when { cond = "`${output}` costs $${metadata.cost}" == "x" score = 0 } } }"#,
        );
        assert!(
            generated.contains(r#"if (`\`${output}\` costs \${metadata.cost}` === "x") {"#),
            "generated:\n{generated}"
        );
    }
}
